# Generated by Django 5.2.1 on 2025-05-21 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('testo', models.TextField()),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroOspiti.autore')),
                ('autoriPreferiti', models.ManyToManyField(related_name='preferiti', to='libroOspiti.autore')),
            ],
        ),
    ]
