# Generated by Django 5.2.1 on 2025-05-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libroOspiti', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autore',
            old_name='cognome',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='autore',
            name='nome',
        ),
    ]
