# Generated by Django 5.2.1 on 2025-05-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libroOspiti', '0002_rename_cognome_autore_username_remove_autore_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commento',
            name='autoriPreferiti',
        ),
    ]
